version: "3.9"
services:
  server:
    build: .
    ports:
      - '4000:4000'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
    volumes:
      - /home/data:/var/lib/postgresql/data
    volumes:
      - /tmp/backup:/tmp/backup
volumes:
  data:
