version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
    volumes:
      - /home/data:/var/lib/postgresql/data
    volumes:
      - /tmp/backup:/tmp/backup
volumes:
  data:
  server:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
