version: "3.9"
services:
  server:
    build: .
    ports:
      - '3000:3000'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
    volumes:
      - /home/data:/var/lib/postgresql/data
    volumes:
      - /var/backup:/var/backup
volumes:
  data:
